name: immich-e2e

services:
  immich-server:
    container_name: immich-e2e-server
    image: immich-server:latest
    build:
      context: ../
      dockerfile: server/Dockerfile
      args:
        - BUILD_ID=1234567890
        - BUILD_IMAGE=e2e
        - BUILD_SOURCE_REF=e2e
        - BUILD_SOURCE_COMMIT=e2eeeeeeeeeeeeeeeeee
    environment:
      - DB_HOSTNAME=database
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - IMMICH_MACHINE_LEARNING_ENABLED=false
      - IMMICH_TELEMETRY_INCLUDE=all
      - IMMICH_ENV=testing
      - IMMICH_PORT=2285
      - IMMICH_IGNORE_MOUNT_CHECK_ERRORS=true
    volumes:
      - ./test-assets:/test-assets
    extra_hosts:
      - 'auth-server:host-gateway'
    depends_on:
      redis:
        condition: service_started
      database:
        condition: service_healthy
    ports:
      - 2285:2285

  redis:
    image: redis:8.2-alpine@sha256:987c376c727652f99625c7d205a1cba3cb2c53b92b0b62aade2bd48ee1593232

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0@sha256:7a4469b9484e37bf2630a60bc2f02f086dae898143b599ecc1c93f619849ef6b
    command: -c fsync=off -c shared_preload_libraries=vchord.so -c config_file=/var/lib/postgresql/data/postgresql.conf
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
    ports:
      - 5435:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d immich']
      interval: 1s
      timeout: 5s
      retries: 30
      start_period: 10s
